
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import 'mac-scrollbar/dist/mac-scrollbar.css';

import type { Metadata } from "next";
import dynamic from 'next/dynamic';

import { Inter } from "next/font/google";
// import { Providers } from "./providers";
import Header from "./components/Header";
import Script from "next/script";


// import { Providers } from "./providers";


const Providers = dynamic(() => import("./providers"), {
  ssr: false
});


// export const runtime = 'nodejs';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <Script src="https://www.google.com/recaptcha/enterprise.js?render=6Lck5V0nAAAAABUIx8PkVTKxvII3cM3z-di43-Vg"></Script>
      <body className={inter.className}>
        <Providers>

          
          <Header />
          {children}
        </Providers>
        
      </body>
    </html>
  );
}